apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-operator-configmap
data:
  config.yaml: |
    service:
      aws:
        accesskey:
          id: "{{.Values.aws.accessKeyId}}"
          secret: "{{.Values.aws.secretAccessKey}}"
          session: "{{.Values.aws.sessionToken}}"
        installationName: "{{.Values.aws.installationName}}"
        region: "{{.Values.aws.region}}"
      kubernetes:
        incluster: true
    server:
      listen:
        address: 'http://0.0.0.0:8000'
