# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"



required = [
  "github.com/docker/distribution/reference",
  "k8s.io/apiserver/pkg/endpoints/request",
  "k8s.io/kubectl/pkg/cmd/util",
  "k8s.io/kubernetes/pkg/kubectl/cmd"
]



[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.29.20"

[[constraint]]
  name = "github.com/aws/amazon-vpc-cni-k8s"
  version = "v1.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/distribution"

[[override]]
  name = "github.com/giantswarm/apiextensions"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/apprclient"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/backoff"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/certs"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/e2e-harness"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/e2eclients"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/e2etemplates"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/e2etests"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/e2esetup"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/exporterkit"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/helmclient"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/ipam"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/k8sclient"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/k8scloudconfig"
  branch = "legacy-with-pv-limit"

[[override]]
  name = "github.com/giantswarm/microendpoint"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/microerror"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/microkit"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/micrologger"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/operatorkit"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/randomkeys"
  version = "~0.1.0"

[[override]]
  name = "github.com/giantswarm/versionbundle"
  version = "~0.1.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.3.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/helm"
  version = "2.16.1"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.16.3"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.16.3"

[[override]]
  name = "sigs.k8s.io/cluster-api"
  version = "~v0.2.8"

[[override]]
  name = "sigs.k8s.io/kustomize"
  version = "v2.0.3"

[[override]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"

[[override]]
  source = "gopkg.in/fsnotify/fsnotify.v1"
  name = "gopkg.in/fsnotify.v1"
  version = "v1.4.7"



[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/giantswarm/k8scloudconfig"
  unused-packages = false
