# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"



required = [
  "github.com/docker/distribution/reference",
  "k8s.io/apiserver/pkg/endpoints/request"
]



[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.14.7"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/giantswarm/apiextensions"
  version = "~0.1.0"

[[constraint]]
  name = "github.com/giantswarm/apprclient"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/backoff"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/certs"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/e2e-harness"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/e2eclients"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/e2etemplates"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/e2etests"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/e2esetup"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/exporterkit"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/helmclient"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/ipam"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/k8scloudconfig"
  version = "~0.1.0"

[[constraint]]
  name = "github.com/giantswarm/microendpoint"
  branch = "master"

[[override]]
  name = "github.com/giantswarm/microerror"
  version = "~0.1.0"

[[constraint]]
  name = "github.com/giantswarm/microkit"
  branch = "master"

[[override]]
  name = "github.com/giantswarm/micrologger"
  version = "~0.1.0"

[[constraint]]
  name = "github.com/giantswarm/operatorkit"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/randomkeys"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/statusresource"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/tenantcluster"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/versionbundle"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.3"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.16.3"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.16.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/helm"
  version = "2.16.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/kubectl"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.16.3"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.16.3"

[[override]]
  name = "sigs.k8s.io/kustomize"
  version = "v2.0.3"

[[override]]
  name = "github.com/evanphx/json-patch"
  version = "4.5.0"

[[override]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"



[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/giantswarm/k8scloudconfig"
  unused-packages = false
