# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"



required = [
  "github.com/docker/distribution/reference",
  "k8s.io/apiserver/pkg/endpoints/request"
]



[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.14.7"

[[constraint]]
  branch = "master"
  name = "github.com/docker/distribution"

[[override]]
  branch = "legacy-1-15"
  name = "github.com/giantswarm/apiextensions"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/apprclient"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/certs"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/e2e-harness"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/e2eclients"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/e2etemplates"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/e2etests"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/e2esetup"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/exporterkit"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/helmclient"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/ipam"

[[constraint]]
  branch = "legacy-fix-conntrack"
  name = "github.com/giantswarm/k8scloudconfig"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microendpoint"

[[override]]
  version = "~0.1.0"
  name = "github.com/giantswarm/microerror"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microkit"

[[override]]
  version = "~0.1.0"
  name = "github.com/giantswarm/micrologger"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/operatorkit"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/randomkeys"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/statusresource"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/tenantcluster"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/versionbundle"

[[override]]
  name = "github.com/google/go-cmp"
  version = "0.3.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  version = "=v0.1.10"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.15.4"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.15.4"

[[override]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "github.com/giantswarm/k8scloudconfig"
  unused-packages = false
