apiVersion: v1
name: aws-operator
description: The aws-operator manages Kubernetes clusters running on AWS.
home: https://github.com/giantswarm/aws-operator
version: [[ .Version ]]
appVersion: [[ .AppVersion ]]
annotations:
  application.giantswarm.io/team: "firecracker"
  config.giantswarm.io/version: "ssopublickey"
