apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: aws-operator
    version: {{ .Chart.Version }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: aws-operator
      version: {{ .Chart.Version }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: aws-operator
        version: {{ .Chart.Version }}
    spec:
      volumes:
      - name: aws-operator-configmap
        configMap:
          name: aws-operator-configmap
          items:
          - key: config.yaml
            path: config.yaml
      - name: aws-operator-secret
        secret:
          secretName: aws-operator-secret
          items:
          - key: secret.yaml
            path: secret.yaml
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
      serviceAccountName: aws-operator
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: aws-operator
        image: {{ .Values.Installation.V1.Registry.Domain }}/giantswarm/aws-operator:[[ .SHA ]]
        volumeMounts:
        - name: aws-operator-configmap
          mountPath: /var/run/aws-operator/configmap/
        - name: aws-operator-secret
          mountPath: /var/run/aws-operator/secret/
          readOnly: true
        - name: certs
          mountPath: /etc/ssl/certs/ca-certificates.crt
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/aws-operator/configmap/
        - --config.dirs=/var/run/aws-operator/secret/
        - --config.files=config
        - --config.files=secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 250Mi
      imagePullSecrets:
      - name: aws-operator-pull-secret
