apiVersion: v1
kind: Service
metadata:
  name: aws-operator.v{{ .Values.version }}
  namespace: {{ .Values.namespace }}
  labels:
    app: aws-operator
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    app: aws-operator
