apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ include "resource.default.name" . }}-exceptions
  namespace: {{ include "resource.default.namespace" . }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  - policyName: restrict-volume-types
    ruleNames:
    - restricted-volumes
    - autogen-restricted-volumes
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - {{ include "resource.default.namespace" . }}
        names:
        - {{ include "resource.default.name" . }}*
